TEAM-Encore/SPRING-BACKEND

- src/main/java/encore/server/domain/post/entity/Post.java
게시글의 임시저장과 공지사항 여부를 확인하기 위한 필드 추가, isNotice, isTemprarySave 필드 추가
> #4 
> Post Entity 변경
> isNotice 필드 추가
> isTemporarySave 필드 추가
> 엔티티 검토 한번 해주세요
> Feat: Post 엔티티 수정 (공지사항 여부와 임시저장 여부 필드 추가)

- src/main/java/encore/server/EncoreServerApplication.java
- src/main/java/encore/server/domain/comment/controller/CommentController.java
- src/main/java/encore/server/domain/comment/converter/CommentConverter.java
- src/main/java/encore/server/domain/comment/dto/request/CommentReq.java
- src/main/java/encore/server/domain/comment/dto/response/CommentRes.java
- src/main/java/encore/server/domain/comment/entity/Comment.java
- src/main/java/encore/server/domain/comment/repository/CommentRepository.java
- src/main/java/encore/server/domain/comment/service/CommentService.java
- src/main/java/encore/server/domain/post/repository/PostRepository.java
- src/main/java/encore/server/domain/user/repository/UserRepository.java
- src/main/java/encore/server/global/exception/ErrorCode.java
- #8 
댓글(대댓글) 생성/수정/조회/삭제 API 개발
>
> Feat: 댓글(대댓글) 생성/수정/조회/삭제 API

- build.gradle
- src/main/java/encore/server/EncoreServerApplication.java
- src/main/java/encore/server/domain/comment/controller/CommentController.java
- src/main/java/encore/server/domain/comment/converter/CommentConverter.java
- src/main/java/encore/server/domain/comment/dto/request/CommentReq.java
- src/main/java/encore/server/domain/comment/dto/response/CommentRes.java
- src/main/java/encore/server/domain/comment/entity/Comment.java
- src/main/java/encore/server/domain/comment/repository/CommentRepository.java
- src/main/java/encore/server/domain/comment/service/CommentService.java
- src/main/java/encore/server/domain/post/repository/PostRepository.java
- src/main/java/encore/server/domain/user/repository/UserRepository.java
- src/main/java/encore/server/global/config/S3Config.java
- src/main/java/encore/server/global/exception/ErrorCode.java
- src/main/java/encore/server/global/util/s3/ImageController.java
- src/main/java/encore/server/global/util/s3/ImageNameDTO.java
- src/main/java/encore/server/global/util/s3/ImageService.java
- #11 
Presigned URL 기반 이미지 업로드 API 개발
>
> Feat: Presigned URL 기반 이미지 업로드 API

- src/main/java/encore/server/domain/comment/controller/CommentController.java
- src/main/java/encore/server/domain/image/controller/ImageController.java
- src/main/java/encore/server/domain/image/dto/ImageNameDTO.java
- src/main/java/encore/server/domain/image/service/ImageService.java
> Fix: 이미지 패키지 및 엔드포인트 수정

- src/main/java/encore/server/domain/image/controller/ImageController.java
- src/main/java/encore/server/domain/post/controller/PostController.java
- src/main/java/encore/server/domain/post/converter/PostConverter.java
- src/main/java/encore/server/domain/post/dto/response/SimplePostRes.java
- src/main/java/encore/server/domain/post/entity/Post.java
- src/main/java/encore/server/domain/post/repository/PostRepository.java
- src/main/java/encore/server/domain/post/repository/PostRepositoryCustom.java
- src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
- src/main/java/encore/server/domain/post/service/PostService.java
- src/main/java/encore/server/domain/user/entity/User.java
- #17 
- [카테고리, 정렬(최신순/인기순), 게시판 종류, 검색어 커서 기반 페이지네이션](https://github.com/TEAM-Encore/SPRING-BACKEND/commit/ea059754f9c40e8a2d68c850680a2147f268db02)
- [해시태그, 정렬 커서 기반 페이지네이션](https://github.com/TEAM-Encore/SPRING-BACKEND/commit/89bdea1c4404b0f732e358085a58edd7586226e7)
>
> Feat: 게시판 커서 기반 페이지네이션

- src/main/java/encore/server/domain/comment/controller/CommentController.java
- src/main/java/encore/server/domain/post/controller/PostController.java
> Fix: Operation 추가

- src/main/java/encore/server/domain/post/controller/PostController.java
- src/main/java/encore/server/domain/post/converter/PostConverter.java
- src/main/java/encore/server/domain/post/dto/response/PostDetailsGetRes.java
- src/main/java/encore/server/domain/post/dto/response/SimplePostRes.java
- src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
- src/main/java/encore/server/domain/post/service/PostService.java
- src/main/java/encore/server/domain/user/entity/User.java
> Fix: 수정사항 반영

- src/main/java/encore/server/domain/post/converter/PostConverter.java
- src/main/java/encore/server/domain/post/entity/Post.java
- src/main/java/encore/server/domain/post/enumerate/Category.java
- src/main/java/encore/server/domain/post/enumerate/PostType.java
- src/main/java/encore/server/domain/post/service/PostService.java
> #23 #22 
> likeCount, commentCount 필드가 추가되어 이에 맞게 Post save시 likeCount, commentCount가 0으로 들어갈 수 있도록 변경함. db default가 0으로 되어있지만 적용이 안되는 것 같아서 코드 상으로 수정
> #23 Fix: Post 엔티티 변경 이후 Post Create 안 되는 버그 수정

- src/main/java/encore/server/domain/post/controller/PostController.java
- src/main/java/encore/server/domain/post/dto/response/PostCreateRes.java
- src/main/java/encore/server/domain/post/dto/response/PostUpdateRes.java
> ex) #28 
> PostCreatRes, PostUpdateRes 추가
> Refactor: PostCreat, PostUpdate 응답 DTO로 변경

- src/main/java/encore/server/domain/post/controller/PostController.java
- src/main/java/encore/server/domain/post/converter/PostConverter.java
- src/main/java/encore/server/domain/post/dto/response/PostDetailsGetRes.java
- src/main/java/encore/server/domain/post/dto/response/SimplePostRes.java
- src/main/java/encore/server/domain/post/repository/PostLikeRepository.java
- src/main/java/encore/server/domain/post/repository/PostRepositoryCustom.java
- src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
- src/main/java/encore/server/domain/post/service/PostService.java
> #36 
> 모든 게시글 조회 API에 좋아요 체크 여부 응답 추가 및 사용자 체크 기능 추가
임시저장 게시물은 조회가 되지 않도록 수정
> Feat: 게시글 조회 API 수정

- src/main/java/encore/server/domain/review/Tag.java
- src/main/java/encore/server/domain/review/entity/Review.java
- src/main/java/encore/server/domain/review/entity/ReviewData.java
- src/main/java/encore/server/domain/review/entity/ViewImage.java
- src/main/java/encore/server/domain/ticket/entity/Ticket.java
- #41 
프리미엄 리뷰 관련 엔티티 수정했습니다~!
>
> Feat: 프리미엄 리뷰 엔티티 수정

- src/main/java/encore/server/domain/post/entity/Post.java
- src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
- src/main/java/encore/server/domain/post/service/PostService.java
- src/main/java/encore/server/domain/review/controller/ReviewController.java
- src/main/java/encore/server/domain/review/converter/ReviewConverter.java
- src/main/java/encore/server/domain/review/dto/request/ReviewReq.java
- src/main/java/encore/server/domain/review/dto/response/ReviewDataRes.java
- src/main/java/encore/server/domain/review/dto/response/ReviewDetailRes.java
- src/main/java/encore/server/domain/review/dto/response/ReviewRes.java
- src/main/java/encore/server/domain/review/dto/response/ViewImageRes.java
- src/main/java/encore/server/domain/review/entity/Review.java
- src/main/java/encore/server/domain/review/entity/ReviewTags.java
- src/main/java/encore/server/domain/review/entity/UserReview.java
- src/main/java/encore/server/domain/review/enumerate/Tag.java
- src/main/java/encore/server/domain/review/repository/ReviewRepository.java
- src/main/java/encore/server/domain/review/repository/ReviewRepositoryCustom.java
- src/main/java/encore/server/domain/review/repository/ReviewRepositoryImpl.java
- src/main/java/encore/server/domain/review/repository/UserReviewRepository.java
- src/main/java/encore/server/domain/review/repository/ViewImageRepository.java
- src/main/java/encore/server/domain/review/service/ReviewService.java
- src/main/java/encore/server/domain/term/entity/Term.java
- src/main/java/encore/server/domain/term/repository/TermRepositoryImpl.java
- src/main/java/encore/server/domain/ticket/entity/Ticket.java
- src/main/java/encore/server/domain/ticket/repository/TicketRepository.java
- src/main/java/encore/server/domain/user/entity/User.java
- src/main/java/encore/server/global/exception/ErrorCode.java
- #43 
- 프리미엄 리뷰 작성 api 개발
- viewImage 조회 개발
>
> Feat: 프리미엄 리뷰 작성 관련 api 개발

- src/main/java/encore/server/EncoreServerApplication.java
- src/main/java/encore/server/domain/review/controller/ReviewController.java
- src/main/java/encore/server/domain/review/converter/ReviewConverter.java
- src/main/java/encore/server/domain/review/dto/response/ReviewDetailRes.java
- src/main/java/encore/server/domain/review/dto/response/ReviewSimpleRes.java
- src/main/java/encore/server/domain/review/entity/Review.java
- src/main/java/encore/server/domain/review/repository/ReviewRepository.java
- src/main/java/encore/server/domain/review/repository/ReviewRepositoryCustom.java
- src/main/java/encore/server/domain/review/repository/ReviewRepositoryImpl.java
- src/main/java/encore/server/domain/review/service/ReviewService.java
- src/main/java/encore/server/domain/review/service/ReviewViewService.java
- src/main/java/encore/server/global/config/RedisConfig.java
- #47 
- 프리미엄 리뷰 조회를 위한 포인트 사용 api
- 프리미엄 리뷰 조회 api
- 유저의 다른 리뷰 조회 api
- 조회수 카운트 api
>
> Feat: 프리미엄 리뷰 조회 관련 api 개발

- src/main/java/encore/server/domain/comment/converter/CommentConverter.java
- src/main/java/encore/server/domain/comment/repository/CommentLikeRepository.java
- src/main/java/encore/server/domain/comment/service/CommentService.java
> Fix: comment Like 조회 수정

- src/main/java/encore/server/domain/ticket/controller/TicketController.java
- src/main/java/encore/server/domain/ticket/converter/TicketConverter.java
- src/main/java/encore/server/domain/ticket/dto/response/TicketRes.java
- src/main/java/encore/server/domain/ticket/dto/response/TicketUpdateRes.java
- src/main/java/encore/server/domain/ticket/entity/Ticket.java
- src/main/java/encore/server/domain/ticket/repository/TicketRepository.java
- src/main/java/encore/server/domain/ticket/service/TicketService.java
> #58 
> 티켓북 조회시 리뷰가 있을 땐 리뷰 총점 함께 조회 가능하도록 구현
>
> Feat : 티켓북에 프리미엄 리뷰 정보 연결

- src/main/java/encore/server/domain/review/controller/ReviewController.java
- src/main/java/encore/server/domain/review/converter/ReviewConverter.java
- src/main/java/encore/server/domain/review/dto/response/ReviewReportRes.java
- src/main/java/encore/server/domain/review/entity/Review.java
- src/main/java/encore/server/domain/review/entity/ReviewReport.java
- src/main/java/encore/server/domain/review/enumerate/ReportReason.java
- src/main/java/encore/server/domain/review/repository/ReviewReportRepository.java
- src/main/java/encore/server/domain/review/service/ReviewService.java
- src/main/java/encore/server/domain/term/repository/TermRepositoryImpl.java
- src/main/java/encore/server/global/exception/ErrorCode.java
- #57 
- 리뷰 수정하기
- 리뷰 삭제하기
- 리뷰 신고하기
신고하기 기능도 추가로 커밋해두었습니다! 
삭제는 논리적 삭제로 해주었고, 현업자분이 리뷰해주신대로 converter는 dto에서 사용하도록 작성했습니다!
> Feat: 리뷰 수정/삭제/신고하기 API

- src/main/java/encore/server/domain/ticket/converter/TicketConverter.java
- src/main/java/encore/server/domain/ticket/dto/response/TicketRes.java
> #73 
> 티켓북 series를 string으로 반환하도록 변경, imageurl 반환 추가
>
> Fix: 티켓북 조회 Response dto 수정

- src/main/java/encore/server/domain/review/service/ReviewService.java
> fix: cast error

- src/main/java/encore/server/domain/post/repository/PostRepository.java
- src/main/java/encore/server/domain/user/controller/UserController.java
- src/main/java/encore/server/domain/user/converter/UserConverter.java
- src/main/java/encore/server/domain/user/dto/request/UserPatchReq.java
- src/main/java/encore/server/domain/user/dto/response/UserGetMeRes.java
- src/main/java/encore/server/domain/user/dto/response/UserNicknameValidationRes.java
- src/main/java/encore/server/domain/user/entity/PreferredKeyword.java
- src/main/java/encore/server/domain/user/entity/TermOfUse.java
- src/main/java/encore/server/domain/user/entity/User.java
- src/main/java/encore/server/domain/user/entity/UserKeyword.java
- src/main/java/encore/server/domain/user/entity/UserTermOfUse.java
- src/main/java/encore/server/domain/user/enumerate/TermType.java
- src/main/java/encore/server/domain/user/enumerate/ViewingFrequency.java
- src/main/java/encore/server/domain/user/repository/PreferredKeywordRepository.java
- src/main/java/encore/server/domain/user/repository/TermOfUseRepository.java
- src/main/java/encore/server/domain/user/repository/UserKeywordRepository.java
- src/main/java/encore/server/domain/user/repository/UserTermOfUseRepository.java
- src/main/java/encore/server/domain/user/service/UserAuthService.java
- src/main/java/encore/server/domain/user/service/UserInfoService.java
- src/main/java/encore/server/domain/user/service/UserSetupService.java
- src/main/java/encore/server/global/auth/OAuth2SuccessHandler.java
- src/main/java/encore/server/global/exception/ErrorCode.java
> #69 #82 
* 유저 닉네임 유효성 검사 API
* 유저 정보 수정 API
* 유저 정보 조회 API
> Feat : 온보딩 페이지에서 필요한 API 구현

- .github/workflows/cicd.yml
- src/main/java/encore/server/domain/review/service/ReviewService.java
> Chore: 잇타 제공 서버 포트로 재배포

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> Deploy: CI/CD 분리

- build.gradle
> Chore: 로그수집 & 모니터링 환경 구축

- src/main/java/encore/server/domain/user/converter/UserConverter.java
> #82 
> 관람주기 정보 조회시 관람주기가 null 일 경우 처리가 없어 발생하던 버그 수정
> [!HOTFIX]  유저 조회 API : 관람주기 정보 조회 버그 수정

- src/main/resources/logback-spring.xml
> [Chore] 로그 수집을 위한 xml 파일 추가

- src/main/resources/logback-spring.xml
#88 
로그 수집을 위한 xml 파일 수정
잇타에서 제공한 서버에 쓰기 권한이 없어서 프롬테일 사용 불가할 것 같습니다..
그래서 바로 loki로 push 하도록 변경하였습니다.
> [Chore] 로그 수집을 위한 xml 파일 수정

- src/main/resources/logback-spring.xml
#88 
Promtail 재적용을 위한 로그수집 xml 파일 수정
쓰기 권한 관련 이슈 해결하여 xml 수정하여 올립니다
> [Chore] Promtail 재적용을 위한 로그수집 xml 파일 수정

- .github/workflows/cd.yml
> Fix: cd.yml 수정

- .github/workflows/ci.yml
> Fix: ci.yml수정

- src/main/java/encore/server/domain/musical/service/MusicalInfoService.java
> Fix: 크롤링 페이지에 더보기 버튼 없는 경우 예외 처리
